export const COPY = {
  badge: 'AI-powered form filler · Phone optimized',
  h1a: 'Form bharne mein',
  h1b: '2 ghante?',
  h1c: 'Ek click. 5 minute.',
  sub: 'SSC, Railway, Police, Banking — koi bhi govt form. Profile ek baar save karo, AI khud sahi values fill kar deta hai. Sab kuch end-to-end encrypted, phone pe optimized.',
  cta: 'Free access ke liye sign up karo',
  ctaSmall: 'Sign up karo',
  timeBefore: 'Bina Laksh ke',
  timeAfter: 'Laksh ke saath',
  timeBeforeNum: '2 ghante',
  timeAfterNum: '5 minute',
  formName: 'SSC CGL Form',
  problemTitle: 'Yeh problem feel hoti hai?',
  problems: [
    { e: '😩', t: 'Har form mein wahi naam, address, DOB type karna' },
    { e: '😡', t: 'Ek typo aur form reject — fir se shuru' },
    { e: '📅', t: 'Notification 4 din baad pata chala, deadline gayi' },
    { e: '📄', t: 'Photo, signature har baar resize karna padta hai' },
  ],
  featuresTitle: 'Laksh kya karta hai',
  features: [
    { e: '🤖', t: 'AI auto-fill', d: 'Ek click karo, AI har field accurately fill kar deta hai. Wahi naam, wahi DOB, har baar.' },
    { e: '🔒', t: 'End-to-end encrypted', d: 'Tumhari profile sirf tumhare phone pe. Hum bhi nahi dekh sakte.' },
    { e: '📱', t: 'Phone pe optimized', d: 'Govt websites desktop ke liye banti hain. Hum manually optimize karte hain — tum phone pe seedha bhar sako.' },
    { e: '🗂️', t: 'Document vault', d: 'Photo, signature, marksheet — sab encrypted, ready to upload, sahi size mein.' },
    { e: '🔔', t: 'Exam alerts', d: 'Sirf tumhari exams ke liye. New form, last date, admit card — WhatsApp pe.' },
  ],
  examsTitle: 'Tumhari exam ke liye banaya hai',
  finalCtaH: 'Form ka tension band karo.',
  finalCtaSub: 'Waitlist join karo. Launch hote hi WhatsApp pe link bhejdenge.',
  footer: 'Made in India 🇮🇳 · Students ke liye',
};
